#!/usr/bin/env bash
# Regenerate Sources/StatusKit/EmojiTable.swift from github/gemoji.
#
# gemoji is the shortcode vocabulary Slack and GitHub share, and it is the only part of "render
# :headphones: as 🎧" that cannot be derived: Unicode's own name for 🎧 is HEADPHONE, and for 🔴 it
# is LARGE RED CIRCLE, so deriving shortcodes from character names would be a guess dressed as a
# lookup (ADR-0014).
#
# The table is *vendored*, not fetched at build or run time — ADR-0004. Run this by hand when the
# vocabulary needs refreshing, and commit the result.
set -euo pipefail

cd "$(dirname "$0")/.."

SOURCE="https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
OUT="Sources/StatusKit/EmojiTable.swift"

scratch=$(mktemp)
trap 'rm -f "$scratch"' EXIT

echo "fetching $SOURCE"
curl -fsSL --max-time 60 "$SOURCE" -o "$scratch"

python3 - "$scratch" "$OUT" "$SOURCE" <<'PY'
import json, sys

raw, out, source = sys.argv[1], sys.argv[2], sys.argv[3]

pairs, seen = [], set()
for entry in json.load(open(raw, encoding="utf-8")):
    glyph = entry.get("emoji")
    if not glyph or any(c.isspace() for c in glyph):
        # The packed format separates pairs by whitespace, so a glyph containing any would make
        # the table ambiguous. None do today; skipping loudly beats emitting something unparseable.
        print(f"skipped {entry.get('aliases')}: glyph contains whitespace", file=sys.stderr)
        continue
    for alias in entry.get("aliases", []):
        if alias in seen or any(c.isspace() for c in alias):
            continue
        seen.add(alias)
        pairs.append((alias, glyph))

# Wrapped on UTF-16 units, which is what SwiftLint counts, and well under its 110 warning.
INDENT, LIMIT = 4, 96


def units(text):
    return len(text.encode("utf-16-le")) // 2


lines, current, width = [], [], INDENT
for alias, glyph in pairs:
    token = f"{alias} {glyph}"
    cost = units(token) + (1 if current else 0)
    if current and width + cost > LIMIT:
        lines.append(" " * INDENT + " ".join(current))
        current, width = [], INDENT
        cost = units(token)
    current.append(token)
    width += cost
if current:
    lines.append(" " * INDENT + " ".join(current))

header = f"""// Generated by scripts/generate-emoji-table.sh — do not edit by hand.
//
// {len(pairs)} shortcode → glyph pairs from github/gemoji, MIT licensed, © GitHub, Inc.:
// {source}
// Vendored as data rather than taken as a dependency (ADR-0004): it changes only when Unicode
// does, and nothing here executes.
//
// Packed as whitespace-separated `shortcode glyph` pairs rather than a dictionary literal: a
// {len(pairs)}-entry `[String: String]` literal is minutes of Swift type-checking, and this parses
// once, lazily, on the first status that needs rendering.

extension EmojiShortcode {{
    static let packed = \"\"\"
{chr(10).join(lines)}
    \"\"\"
}}
"""

open(out, "w", encoding="utf-8").write(header)
print(f"wrote {out}: {len(pairs)} pairs, {len(lines)} packed lines")
PY
