#!/usr/bin/env bash
# Regenerate Sources/StatusKit/EmojiTable.swift from github/gemoji.
#
# gemoji is the shortcode vocabulary Slack and GitHub share, and it is the only part of "render
# :headphones: as 🎧" that cannot be derived: Unicode's own name for 🎧 is HEADPHONE, and for 🔴 it
# is LARGE RED CIRCLE, so deriving shortcodes from character names would be a guess dressed as a
# lookup (ADR-0014).
#
# The table is *vendored*, not fetched at build or run time — ADR-0004. Run this by hand when the
# vocabulary needs refreshing, and commit the result.
set -euo pipefail

cd "$(dirname "$0")/.."

# Pinned to a tag, not to `master`: the output of this script is compiled into a process that holds
# a Slack user token, so "whatever upstream contained today" is not an acceptable trust anchor.
# Bump the tag deliberately, re-run, and read the diff.
SOURCE="https://raw.githubusercontent.com/github/gemoji/v4.1.0/db/emoji.json"
OUT="Sources/StatusKit/EmojiTable.swift"

scratch=$(mktemp)
trap 'rm -f "$scratch"' EXIT

echo "fetching $SOURCE"
curl -fsSL --max-time 60 "$SOURCE" -o "$scratch"

python3 - "$scratch" "$OUT" "$SOURCE" <<'PY'
import json, re, sys

raw, out, source = sys.argv[1], sys.argv[2], sys.argv[3]

# Everything below goes verbatim into a Swift `"""` literal, and Swift interpolates `\(...)` inside
# one. An upstream alias of `\(anything())` would therefore become *code* in a process holding a
# Slack token — so the shapes are enforced here, before compilation, and a violation aborts the
# generation rather than being skipped. The suite re-checks the same two shapes afterwards, but by
# then any payload has already compiled.
ALIAS = re.compile(r"\A[a-z0-9_+-]+\Z")


def refuse(reason):
    raise SystemExit(f"refusing to generate: {reason}")


pairs, seen = [], set()
for entry in json.load(open(raw, encoding="utf-8")):
    glyph = entry.get("emoji")
    aliases = entry.get("aliases", [])
    if not glyph:
        print(f"skipped {aliases}: no glyph", file=sys.stderr)
        continue
    if any(c.isspace() or c in '\\"' for c in glyph):
        # Whitespace would make the packed format ambiguous. A backslash is how `\(interpolation)`
        # would arrive and a quote is how the `\"\"\"` terminator would; neither belongs in an emoji.
        refuse(f"glyph for {aliases} is not a bare emoji: {glyph!r}")
    if all(ord(c) < 128 for c in glyph):
        # Keycaps like #️⃣ legitimately start with an ASCII character, so the bar is "carries at
        # least one non-ASCII scalar" — the same shape the suite asserts, which is what keeps a
        # shifted pack detectable.
        refuse(f"glyph for {aliases} carries no non-ASCII scalar: {glyph!r}")
    for alias in aliases:
        if not ALIAS.match(alias):
            refuse(f"alias {alias!r} is not [a-z0-9_+-]+")
        if alias in seen:
            continue
        seen.add(alias)
        pairs.append((alias, glyph))

if not pairs:
    refuse("no pairs survived; the source shape has changed")

# Wrapped on UTF-16 units, which is what SwiftLint counts, and well under its 110 warning.
INDENT, LIMIT = 4, 96


def units(text):
    return len(text.encode("utf-16-le")) // 2


lines, current, width = [], [], INDENT
for alias, glyph in pairs:
    token = f"{alias} {glyph}"
    cost = units(token) + (1 if current else 0)
    if current and width + cost > LIMIT:
        lines.append(" " * INDENT + " ".join(current))
        current, width = [], INDENT
        cost = units(token)
    current.append(token)
    width += cost
if current:
    lines.append(" " * INDENT + " ".join(current))

header = f"""// Generated by scripts/generate-emoji-table.sh — do not edit by hand.
//
// {len(pairs)} shortcode → glyph pairs from github/gemoji, MIT licensed, © GitHub, Inc.:
// {source}
// Vendored as data rather than taken as a dependency (ADR-0004): it changes only when Unicode
// does, and nothing here executes.
//
// Packed as whitespace-separated `shortcode glyph` pairs rather than a dictionary literal: a
// {len(pairs)}-entry `[String: String]` literal is minutes of Swift type-checking, and this parses
// once, lazily, on the first status that needs rendering.

extension EmojiShortcode {{
    static let packed = \"\"\"
{chr(10).join(lines)}
    \"\"\"
}}
"""

open(out, "w", encoding="utf-8").write(header)
print(f"wrote {out}: {len(pairs)} pairs, {len(lines)} packed lines")
PY
